@startuml
'skinparam svgDimensionStyle false
autonumber

== Create Request ==

note over Placer,Fulfiller
Assume endpoints, client registration, business rules, etc. 
are communicated beforehand and that subscriptions already initiated
end note

||45||

Placer -> Placer : Create local representation, ServiceRequest

Placer -> Fulfiller : POST Task to Fulfiller with ServiceRequest in Task.basedOn

Fulfiller <-- Fulfiller: Create Local Representation

||45||

note over Placer,Fulfiller
Based on business agreements, no confirmation needed of the HTTP status code. 
The Placer may assume the Fulfiller accepts the request. 
end note

||45||

== If Generating Output == 

Fulfiller <- Fulfiller : Create Output Document (of some\nform, if needed) and host on FHIR server

Fulfiller <- Fulfiller: Update Task.Output

group if using Subscriptions:
    Placer <- Fulfiller: send SubscriptionStatusNotification for Task update
end

note over Placer,Fulfiller: Note - implementers should be mindful of performance considerations to polling
group if not using Subscriptions:
    Placer -> Fulfiller: Poll Fulfiller periodically to see if Service complete
    Fulfiller -> Placer: Respond with Info
end

Placer --> Placer : Create local-representation as needed
@enduml
